sudo: false  # Use container-based infrastructure
language: node_js
node_js:
  - "10.15"
dist: trusty # chrome addon needs trusty
addons:
  chrome: stable
script: >
    npm run build &&
    npm run test &&
    npm run flow-check &&
    npm run lint &&
    npm run coverage &&
    ./scripts/post-coverage.sh
